import type { SiteContent } from "./types";

export const cs: SiteContent = {
  meta: {
    title: "Real Meal Global — Jídlo bez hranic",
    description:
      "Trvanlivá hotová jídla s vysokým obsahem bílkovin. 24 měsíců trvanlivosti bez nutnosti chlazení. Strategické partnerství Real Meal a Astra Food.",
  },
  nav: {
    about: "O nás",
    offer: "Platformy",
    contact: "Kontakt",
    cta: "Staňte se partnerem",
    skipToContent: "Přejít na hlavní obsah",
  },
  hero: {
    kicker: "Partnerství s Astra Food",
    badge: "24 měsíců · Bez chlazení",
    title: ["Globální platforma", "hotových jídel"],
    subtitle: "Real Meal. Jídlo bez hranic. Připravené pro celý svět.",
    description:
      "Budujeme příštího globálního lídra v prémiových trvanlivých bílkovinových jídlech — pro retail, gastronomii, obranu a humanitární sektor.",
    ctaPrimary: "Staňte se partnerem",
    ctaSecondary: "Prozkoumat platformu",
    confidential: "Informace pro investory a partnery",
  },
  stats: {
    caption: "Stavíme na zavedeném evropském výrobním ekosystému.",
    items: [
      { value: "24", unit: "měsíců", label: "Trvanlivost bez nutnosti chlazení" },
      { value: "1M+", unit: "jídel", label: "Měsíční výroba napříč ekosystémem" },
      { value: "30+", unit: "let", label: "Zkušeností v potravinářské výrobě" },
      { value: "200K+", unit: "jídel", label: "Připraveno k rychlému nasazení v krizi" },
    ],
  },
  cta: {
    afterOffer: {
      title: "Osm způsobů, jak dostat trvanlivé bílkoviny na váš trh.",
      body: "Řekněte nám, který pilíř sedí vašemu byznysu, a připravíme konkrétní nabídku — objemy, receptury, balení i logistiku.",
      button: "Probrat partnerství",
    },
    afterAsk: {
      title: "Odpovídá vaše organizace některému z těchto profilů?",
      body: "Otevíráme distribuční a white-label partnerství trh po trhu.",
      button: "Začít jednání",
    },
    mobileBar: {
      message: "Staňte se partnerem Real Meal Global",
      button: "Kontakt",
      dismiss: "Zavřít",
    },
  },
  credibility: {
    whoWeAre: {
      kicker: "Kdo jsme",
      title: "Strategické partnerství mezi Real Meal a Astra Food.",
      subtitle: "Podpořeno desítkami let výrobních zkušeností.",
      realMeal: {
        title: "Real Meal",
        points: [
          "Globální platforma hotových jídel",
          "30+ let zkušeností v potravinářské výrobě",
          "Špičkové výrobní kapacity",
          "Mezinárodní certifikace bezpečnosti potravin",
        ],
      },
      astraFood: {
        title: "Astra Food",
        points: [
          "Ověřená výrobní kapacita pro globální trhy",
          "Jeden z předních výrobců potravin ve střední a východní Evropě (CEE)",
          "Dlouholeté zkušenosti s OEM a private label výrobou",
          "Unikátní technologie umožňující dlouhou trvanlivost bez chlazení",
        ],
      },
      closing:
        "Nejde o startup bez výrobní kapacity — jde o silné partnerství postavené na desítkách let výrobních zkušeností.",
    },
    ecosystem: {
      kicker: "Náš potravinový ekosystém",
      title: "Jeden výrobní ekosystém. Tři potravinové platformy.",
      subtitle: "Astra Foods × Real Meal",
      intro:
        "Kompletní potravinový ekosystém, který obsluhuje různé trhy prostřednictvím tří vzájemně se doplňujících obchodních platforem.",
      metric: { value: "3", unit: "platformy", label: "Jeden sdílený výrobní ekosystém" },
      platforms: [
        {
          name: "Globální platforma hotových jídel",
          focus: "V centru pozornosti",
          points: [
            "Trvanlivost 24 měsíců",
            "Bez nutnosti chlazení",
            "Připraveno k odeslání kamkoliv na světě",
            "K dispozici i HALAL varianta",
            "Vlády a obrana",
            "Humanitární pomoc",
            "Retail",
            "White Label / OEM",
          ],
          highlight: true,
        },
        {
          name: "Chlazená hotová jídla",
          points: [
            "1M+ jídel měsíčně",
            "Distribuce po celém regionu CEE",
            "Chlazený dodavatelský řetězec",
            "Retail a gastronomie",
            "Ověřená výrobní škála",
          ],
          highlight: false,
        },
        {
          name: "Čerstvé denní jídlo",
          points: [
            "Poke by Simona",
            "Čerstvé sendviče",
            "Čerstvé svačiny",
            "Denní výroba",
            "Denní distribuce",
          ],
          highlight: false,
        },
      ],
      footer: "Jeden výrobní ekosystém. Tři obchodní platformy. Jedna globální vize.",
    },
    globalStructure: {
      kicker: "Globální struktura",
      title: "Vyrobeno v Evropě. Produkce v České republice. Globálně řízeno z Dubaje.",
      subtitle: "Výrobní excelence propojená s globálním dosahem.",
      metric: { value: "4", unit: "regiony", label: "Evropa, Blízký východ, Afrika a Asie řízené z Dubaje" },
      manufacturing: {
        location: "Česká republika — výrobní excelence",
        points: [
          "Jeden z předních výrobců potravin v regionu CEE",
          "30+ let zkušeností v potravinářské výrobě",
          "Unikátní výrobní technologie",
          "Mezinárodní certifikace bezpečnosti potravin",
          "Flexibilní výrobní kapacita",
          "Prémiová evropská kvalita",
          "Zkušenosti s OEM a Private Label výrobou",
        ],
      },
      sales: {
        location: "Dubaj — globální obchodní centrála",
        points: [
          "Globální obchodní centrála",
          "Mezinárodní rozvoj byznysu",
          "Celosvětová síť partnerů",
          "Strategický uzel spojující Evropu, Blízký východ, Afriku a Asii",
          "Rychlý přístup na globální trhy",
          "Řízení celosvětové distribuce",
        ],
      },
    },
    manufacturing: {
      kicker: "Výrobní excelence",
      title: "Více než tři desítky let výrobních zkušeností.",
      subtitle: "Certifikováno, flexibilní a připraveno na růst.",
      metric: { value: "3", unit: "certifikace", label: "IFS, HACCP a HALAL — další na vyžádání" },
      productionLabel: "Výroba",
      production: [
        "Flexibilní výrobní kapacita",
        "Vysokoobjemová výroba",
        "K dispozici HALAL výroba",
        "OEM a Private Label",
        "Mezinárodní standardy kvality",
      ],
      certificationsLabel: "Certifikace",
      certifications: ["IFS", "HACCP", "HALAL"],
      certificationsNote: "Další certifikace na vyžádání",
      flexibilityLabel: "Provozní flexibilita",
      flexibility: [
        "Škálovatelná výroba",
        "Kontejnerové zásilky",
        "Krátké dodací lhůty",
        "Dlouhodobá strategická partnerství",
      ],
    },
  },
  offer: {
    kicker: "Hlavní byznys",
    title: "Budoucnost bílkovin nepotřebuje chlazení.",
    intro: "Je trvanlivá, globálně škálovatelná a připravená obsloužit miliony lidí.",
    coreLabel: "Naše dva hlavní obchodní pilíře",
    corePillars: [
      {
        title: "Prémiové masné kolekce s vysokým obsahem bílkovin",
        points: ["Hovězí", "Kuřecí", "Halal", "Trvanlivost 24 měsíců"],
      },
      {
        title: "Kolekce hotových jídel",
        points: ["Kompletní jídla", "Příprava za 2 minuty", "Bez nutnosti chlazení", "Retail a gastronomie"],
      },
    ],
    growthLabel: "Rozšíření platformy — osm růstových pilířů",
    growthIntro:
      "Jeden výrobní ekosystém, osm cest na každý trh — od pultů obchodů až po oblasti zasažené krizí.",
    benefitsLabel: "Klíčové přínosy",
    detailsLabel: "Zobrazit detail",
    closeLabel: "Zavřít",
    growthPillars: [
      {
        number: "01",
        title: "Prémiová masná řešení",
        short: "Pomalu vařené trhané hovězí a kuřecí, plně uvařené a hotové během minut.",
        description:
          "Naše pomalu vařené prémiové trhané hovězí a kuřecí maso je plně uvařené a připravené k použití během pár minut. Ideální pro retail, gastronomii, catering, armádu, humanitární pomoc i mezinárodní distribuci. K dispozici v hovězí, kuřecí a HALAL variantě.",
        benefits: [
          "24 měsíců trvanlivosti",
          "Vakuově balené porce",
          "Bez nutnosti chlazení",
          "Snadná globální logistika",
          "Plně uvařené",
          "Baleno do maloobchodních krabic",
          "Vysoký obsah bílkovin",
          "Připraveno během pár minut",
        ],
        tags: ["24 měsíců trvanlivosti", "Bez chlazení", "Vakuově baleno", "Vysoký obsah bílkovin", "Připraveno za pár minut"],
      },
      {
        number: "02",
        title: "Hotová jídla",
        short: "Nejoblíbenější recepty světa jako kompletní jídla, teplá za dvě minuty.",
        description:
          "Kompletní portfolio chutných hotových jídel inspirovaných nejoblíbenějšími recepty světa. Vyvíjíme také regionální recepty přizpůsobené místním trhům a preferencím zákazníků.",
        benefits: [
          "24 měsíců trvanlivosti",
          "Připraveno k jídlu za 2 minuty",
          "Bez nutnosti chlazení",
          "Vývoj regionálních receptur",
          "Plně uvařená jídla",
          "Vakuově baleno",
          "Evropská výroba",
          "Prémiová chuť",
        ],
        tags: ["24 měsíců trvanlivosti", "Připraveno za 2 minuty", "Bez chlazení", "Evropská výroba", "Prémiová chuť"],
      },
      {
        number: "03",
        title: "Humanitární pomoc",
        short: "Jídlo k rychlému nasazení pro vlády, neziskovky a vojenské mise.",
        description:
          "Rychlá a spolehlivá potravinová řešení pro vlády, nevládní organizace, vojenské složky a humanitární mise po celém světě. Navrženo pro rychlé nasazení všude tam, kde je potřeba zajistit potravinovou bezpečnost.",
        benefits: [
          "Až 200 000 jídel k okamžitému nasazení",
          "Letecká, námořní i pozemní přeprava",
          "Vysoká nutriční hodnota",
          "Globální logistická podpora",
          "24 měsíců trvanlivosti",
          "Bez nutnosti chlazení",
          "Připraveno během pár minut",
          "Řešení pro krizové situace",
        ],
        tags: ["200K+ jídel k dispozici", "24 měsíců trvanlivosti", "Bez chlazení", "Rychlé nasazení", "Globální logistika"],
      },
      {
        number: "04",
        title: "Rodinné nouzové potravinové balíčky",
        short: "Balíčky dlouhodobé potravinové jistoty pro domácnosti a rodiny.",
        description:
          "Kompletní nouzová potravinová řešení navržená pro domácnosti a rodiny, aby zajistila dlouhodobou potravinovou bezpečnost v neočekávaných situacích. K dispozici pro různé velikosti rodin a doby skladování.",
        benefits: [
          "24 měsíců trvanlivosti",
          "Masné i vegetariánské varianty",
          "Kompaktní skladování",
          "Připravenost na nouzové situace",
          "Kompletní zásoba jídla pro rodinu",
          "Vyvážená výživa",
          "Připraveno během pár minut",
          "Řešení pro bezpečí domácnosti",
        ],
        tags: ["24 měsíců trvanlivosti", "Kompletní zásoba pro rodinu", "Kompaktní skladování", "Připraveno za pár minut", "Nouzová připravenost"],
      },
      {
        number: "05",
        title: "Celebrity food lines",
        short: "Prémiové co-brandované řady se sportovci a mediálními osobnostmi.",
        description:
          "Vytváříme prémiové potravinové značky společně s celebritami, sportovci, influencery a mediálními osobnostmi. Zahrnuje vývoj receptur, branding, balení, výrobu i celosvětovou distribuci.",
        note: "Příklad: Jakub Vágner, mezinárodně uznávaný rybář a bývalá osobnost National Geographic a Discovery.",
        benefits: [
          "Branding s celebritou",
          "Prémiové balení",
          "Celosvětová distribuce",
          "Produkty připravené pro retail",
          "Marketing na sociálních sítích",
          "Globální výroba",
          "Kompletní správa značky",
          "24 měsíců trvanlivosti",
        ],
        tags: ["Branding s celebritou", "Globální výroba", "Celosvětová distribuce", "24 měsíců trvanlivosti"],
      },
      {
        number: "06",
        title: "White Label výroba",
        short: "Výroba na klíč pod vaší vlastní značkou.",
        description:
          "Vyvíjíme a vyrábíme kompletní kolekce hotových jídel pod vlastními značkami našich partnerů. Od vývoje receptur přes design obalů a vícejazyčné etikety až po celosvětovou distribuci — poskytujeme kompletní řešení na klíč.",
        benefits: [
          "24 měsíců trvanlivosti",
          "OEM výroba",
          "Vícejazyčné balení",
          "Evropská výroba",
          "Výroba pod privátní značkou",
          "Receptury na míru",
          "Celosvětová logistika",
          "Flexibilní výrobní objemy",
        ],
        tags: ["24 měsíců trvanlivosti", "OEM výroba", "Receptury na míru", "Celosvětová logistika", "Evropská výroba"],
      },
      {
        number: "07",
        title: "Protein Bomb Fitness kolekce",
        short: "48–49 g bílkovin, sous-vide, stvořeno pro sportovce.",
        description:
          "Masná kolekce s vysokým obsahem bílkovin, vařená metodou sous-vide, navržená pro sportovce, fitness nadšence a aktivní životní styl.",
        note: "Vyvinuto ve spolupráci s Karlem Vémolou, MMA legendou a globálním fitness ambasadorem.",
        benefits: [
          "48–49 g bílkovin na balení",
          "Vařeno metodou sous-vide",
          "Vysoký obsah bílkovin",
          "24 měsíců trvanlivosti",
          "Připraveno k jídlu",
          "Bez nutnosti chlazení",
          "Vakuová balení 2×250 g",
          "Stvořeno pro výkon",
        ],
        tags: ["48–49 g bílkovin", "Vařeno sous-vide", "Vysoký obsah bílkovin", "Bez chlazení", "24 měsíců trvanlivosti"],
      },
      {
        number: "08",
        title: "Instant Power Bowl",
        short: "Instantní nudlové misky — stačí horká voda, hotovo za tři minuty.",
        description:
          "Prémiové instantní nudlové misky navržené pro kancelářské pracovníky, studenty, cestování i každodenní pohodlí. Stačí přidat horkou vodu a vychutnat si skutečné jídlo kdykoliv a kdekoliv.",
        benefits: [
          "Stačí přidat horkou vodu",
          "Připraveno za 3 minuty",
          "Vysoký obsah bílkovin",
          "Skutečné ingredience",
          "Praktické a přenosné",
          "Lehké",
          "Dlouhá trvanlivost",
          "Ideální na cesty",
        ],
        tags: ["Stačí horká voda", "Připraveno za 3 minuty", "Vysoký obsah bílkovin", "Skutečné ingredience", "Přenosné"],
      },
    ],
  },
  ask: {
    lookingFor: {
      kicker: "Koho hledáme",
      title: "Strategické partnery pro celosvětové škálování platformy.",
      intro:
        "Hledáme dlouhodobé strategické partnery a distributory pro expanzi naší globální platformy hotových jídel po celém světě.",
      groups: [
        {
          title: "Vlády a veřejný sektor",
          items: ["Vlády", "Armáda a obrana", "Civilní ochrana", "Humanitární organizace", "Krizové agentury"],
        },
        {
          title: "Potravinářští a retailoví partneři",
          items: ["Výrobci potravin", "Distributoři potravin", "Retailové řetězce", "Online potravinové platformy", "Sítě večerek"],
        },
        {
          title: "Strategičtí a komerční partneři",
          items: ["Investiční fondy", "Family offices", "Private equity", "Hotelnictví a letecké společnosti", "Globální strategičtí partneři"],
        },
      ],
      closing: "Hledáme strategické partnery pro vybudování přední světové platformy hotových jídel.",
    },
    closing: {
      lines: [
        "Svět nepotřebuje další potravinářskou firmu.",
        "Svět potřebuje jídlo bez limitů.",
        "Jídlo, které překračuje hranice.",
        "Jídlo, které se dostane do oblastí zasažených katastrofou.",
        "Jídlo, které živí komunity.",
        "Jídlo, které podporuje vlády.",
        "Jídlo, které pomáhá rodinám se připravit.",
        "Jídlo, které vytváří nové příležitosti pro globální značky.",
        "Proto Real Meal existuje.",
      ],
      tagline: "Jídlo bez hranic. Připravené pro celý svět.",
    },
  },
  contact: {
    kicker: "Kontaktujte nás",
    title: "Pojďme společně budovat budoucnost jídla.",
    subtitle: "Jídlo bez hranic. Připravené pro celý svět.",
    photoAlt: "Portrét: {name}",
    people: [
      {
        name: "Tomáš Skácel",
        role: "Zakladatel | Akcionář | Globální CEO",
        photo: "/team/skacel.webp",
        phone: "+420 606 806 060",
        email: "tomas.skacel@astrafood.cz",
      },
      {
        name: "Ondřej Pernecký",
        role: "Ředitel globálního obchodního rozvoje a prodeje",
        photo: "/team/pernecky.webp",
        phone: "+420 739 177 819",
        email: "ondrej.pernecky@astrafood.cz",
      },
      {
        name: "Karel Vágner",
        role: "Akcionář | Řídící partner | Globální obchodní rozvoj a strategická partnerství",
        photo: "/team/vagner.webp",
        phone: "+420 602 312 154",
        email: "karel.vagner@real-meal.cz",
        instagram: "@karelvagner",
      },
      {
        name: "Simona Krainová",
        role: "Akcionářka | Globální ambasadorka značky | Ambasadorka pro humanitární a společenský dopad",
        photo: "/team/krainova.webp",
        instagram: "@simonakrainova",
        note: "Top modelka, influencerka, cestovatelka",
      },
    ],
    form: {
      name: "Celé jméno",
      email: "E-mail",
      company: "Firma / organizace",
      message: "Popište váš zájem o partnerství",
      submit: "Odeslat poptávku",
      success: "Děkujeme, ozveme se vám.",
      responseTime: "Na poptávky ohledně partnerství odpovídáme do 2 pracovních dnů.",
      privacy: "Vaše údaje použijeme pouze k zodpovězení této poptávky a nepředáváme je třetím stranám.",
    },
    footer: {
      note: "Real Meal Global — strategické partnerství mezi Real Meal a Astra Food.",
      links: "astrafood.cz · real-meal.cz · real-mealglobal.com",
      copyright: "Real Meal Global. Všechna práva vyhrazena.",
    },
  },
};
