import type { SiteContent } from "./types";

export const en: SiteContent = {
  meta: {
    title: "Real Meal Global — Food Without Borders",
    description:
      "Shelf-stable, ready-to-eat protein meals. 24-month shelf life, no refrigeration required. A strategic partnership between Real Meal and Astra Food.",
  },
  nav: {
    about: "About",
    offer: "Platforms",
    contact: "Contact",
    cta: "Partner With Us",
    skipToContent: "Skip to main content",
  },
  hero: {
    kicker: "Astra Food Partnership",
    badge: "24 Months · No Refrigeration",
    title: ["Global Ready-to-Eat", "Meal Platform"],
    subtitle: "Real Meal. Food without borders. Ready for the world.",
    description:
      "Building the next global leader in shelf-stable premium protein meals — for retail, foodservice, defence and humanitarian markets.",
    ctaPrimary: "Become a Partner",
    ctaSecondary: "Explore the Platform",
    confidential: "Investor & Partner Information",
  },
  stats: {
    caption: "Backed by an established European production ecosystem.",
    items: [
      { value: "24", unit: "months", label: "Shelf life without refrigeration" },
      { value: "1M+", unit: "meals", label: "Produced monthly across the ecosystem" },
      { value: "30+", unit: "years", label: "Of food manufacturing experience" },
      { value: "200K+", unit: "meals", label: "Ready for rapid crisis deployment" },
    ],
  },
  cta: {
    afterOffer: {
      title: "Eight ways to bring shelf-stable protein to your market.",
      body: "Tell us which pillar fits your business and we will put together a concrete proposal — volumes, recipes, packaging and logistics.",
      button: "Discuss a partnership",
    },
    afterAsk: {
      title: "Does your organization fit one of these profiles?",
      body: "We are opening distribution and white-label partnerships market by market.",
      button: "Start the conversation",
    },
    mobileBar: {
      message: "Partner with Real Meal Global",
      button: "Contact",
      dismiss: "Dismiss",
    },
  },
  credibility: {
    whoWeAre: {
      kicker: "Who We Are",
      title: "A strategic partnership between Real Meal and Astra Food.",
      subtitle: "Backed by decades of manufacturing.",
      realMeal: {
        title: "Real Meal",
        points: [
          "Global Ready-to-Eat Meal Platform",
          "30+ years of food manufacturing experience",
          "State-of-the-art production facilities",
          "International food safety certifications",
        ],
      },
      astraFood: {
        title: "Astra Food",
        points: [
          "Proven manufacturing capacity for global markets",
          "One of the leading food manufacturers in Central & Eastern Europe (CEE)",
          "Long-term OEM & private label expertise",
          "Unique technology enabling long shelf-life without refrigeration",
        ],
      },
      closing:
        "This is not a startup without production capacity — it is a strong partnership built on decades of manufacturing experience.",
    },
    ecosystem: {
      kicker: "Our Food Ecosystem",
      title: "One Production Ecosystem. Three Food Platforms.",
      subtitle: "Astra Foods × Real Meal",
      intro:
        "A complete food ecosystem serving different markets through three complementary business platforms.",
      metric: { value: "3", unit: "platforms", label: "One shared production ecosystem" },
      platforms: [
        {
          name: "Global Ready-to-Eat Meal Platform",
          focus: "Today's Focus",
          points: [
            "24-month shelf life",
            "No refrigeration required",
            "Ready to ship worldwide",
            "Halal available",
            "Government & Defence",
            "Humanitarian Aid",
            "Retail",
            "White Label / OEM",
          ],
          highlight: true,
        },
        {
          name: "Chilled Ready Meals",
          points: [
            "1M+ meals produced monthly",
            "Distributed across CEE",
            "Refrigerated supply chain",
            "Retail & Foodservice",
            "Proven manufacturing scale",
          ],
          highlight: false,
        },
        {
          name: "Fresh Daily Food",
          points: [
            "Poke by Simona",
            "Fresh sandwiches",
            "Fresh snacks",
            "Daily production",
            "Daily distribution",
          ],
          highlight: false,
        },
      ],
      footer: "One production ecosystem. Three business platforms. One global vision.",
    },
    globalStructure: {
      kicker: "Global Structure",
      title: "Made in Europe. Produced in the Czech Republic. Globally Managed from Dubai.",
      subtitle: "Manufacturing excellence meets global reach.",
      metric: { value: "4", unit: "regions", label: "Europe, Middle East, Africa and Asia served from Dubai" },
      manufacturing: {
        location: "Czech Republic — Manufacturing Excellence",
        points: [
          "One of the leading food manufacturers in the CEE region",
          "30+ years of food manufacturing experience",
          "Unique production technology",
          "International food safety certifications",
          "Flexible production capacity",
          "Premium European quality",
          "OEM & Private Label expertise",
        ],
      },
      sales: {
        location: "Dubai — Global Sales & Headquarters",
        points: [
          "Global Sales & Business Headquarters",
          "International Business Development",
          "Worldwide partner network",
          "Strategic hub connecting Europe, Middle East, Africa and Asia",
          "Fast access to global markets",
          "Worldwide distribution management",
        ],
      },
    },
    manufacturing: {
      kicker: "Manufacturing Excellence",
      title: "More than three decades of manufacturing expertise.",
      subtitle: "Certified, flexible, and built for scale.",
      metric: { value: "3", unit: "certifications", label: "IFS, HACCP and HALAL — more on request" },
      productionLabel: "Production",
      production: [
        "Flexible production capacity",
        "High-volume manufacturing",
        "HALAL production available",
        "OEM & Private Label",
        "International quality standards",
      ],
      certificationsLabel: "Certifications",
      certifications: ["IFS", "HACCP", "HALAL"],
      certificationsNote: "Additional certifications upon request",
      flexibilityLabel: "Operational Flexibility",
      flexibility: [
        "Scalable production",
        "Container shipments",
        "Short lead times",
        "Long-term strategic partnerships",
      ],
    },
  },
  offer: {
    kicker: "Core Business",
    title: "The future of protein is not refrigerated.",
    intro: "It is shelf-stable, globally scalable and ready to serve millions.",
    coreLabel: "Our Two Core Business Pillars",
    corePillars: [
      {
        title: "Premium High-Protein Meat Collections",
        points: ["Beef", "Chicken", "Halal", "24 Months Shelf Life"],
      },
      {
        title: "Ready-to-Eat Meal Collection",
        points: ["Complete Meals", "2 Minutes Preparation", "No Refrigeration Required", "Retail & Foodservice"],
      },
    ],
    growthLabel: "Platform Expansion — Eight Growth Pillars",
    growthIntro:
      "One production ecosystem, eight ways to reach every market — from retail shelves to disaster zones.",
    benefitsLabel: "Key benefits",
    detailsLabel: "View details",
    closeLabel: "Close",
    growthPillars: [
      {
        number: "01",
        title: "Premium Meat Solutions",
        short: "Slow-cooked shredded beef and chicken, fully cooked and ready in minutes.",
        description:
          "Our slow-cooked premium shredded beef and chicken are fully cooked and ready to use in minutes. Perfect for retail, food service, catering, military, humanitarian aid and international distribution. Available in Beef, Chicken and Halal collections.",
        benefits: [
          "24 months shelf life",
          "Vacuum packed portions",
          "No refrigeration required",
          "Easy global logistics",
          "Fully cooked",
          "Packed in retail boxes",
          "High protein",
          "Ready in minutes",
        ],
        tags: ["24 Months Shelf Life", "No Refrigeration", "Vacuum Packed", "High Protein", "Ready in Minutes"],
      },
      {
        number: "02",
        title: "Ready-to-Eat Meals",
        short: "World-favourite recipes as complete meals, hot in two minutes.",
        description:
          "A complete portfolio of delicious ready meals inspired by the world's most popular recipes. We also develop regional recipes tailored to local markets and customer preferences.",
        benefits: [
          "24 months shelf life",
          "Ready to eat in 2 minutes",
          "No refrigeration required",
          "Regional recipe development",
          "Fully cooked meals",
          "Vacuum packed",
          "European production",
          "Premium taste",
        ],
        tags: ["24 Months Shelf Life", "Ready in 2 Minutes", "No Refrigeration", "European Production", "Premium Taste"],
      },
      {
        number: "03",
        title: "Humanitarian Aid",
        short: "Rapid-deployment food for governments, NGOs and military missions.",
        description:
          "Fast, reliable food solutions for governments, NGOs, military organizations and humanitarian missions worldwide. Designed for rapid deployment wherever food security is needed.",
        benefits: [
          "Up to 200,000 meals ready",
          "Air, sea or land transport",
          "High nutritional value",
          "Global logistics support",
          "24 months shelf life",
          "No refrigeration required",
          "Ready in minutes",
          "Crisis response solutions",
        ],
        tags: ["200K+ Meals Ready", "24 Months Shelf Life", "No Refrigeration", "Rapid Deployment", "Global Logistics"],
      },
      {
        number: "04",
        title: "Family Emergency Food Packs",
        short: "Long-term food security packs sized for households and families.",
        description:
          "Complete emergency food solutions designed for households and families to ensure long-term food security during unexpected situations. Available for different family sizes and storage periods.",
        benefits: [
          "24 months shelf life",
          "Meat & vegetarian options",
          "Compact storage",
          "Emergency preparedness",
          "Complete family food supply",
          "Balanced nutrition",
          "Ready in minutes",
          "Home safety solution",
        ],
        tags: ["24 Months Shelf Life", "Complete Family Supply", "Compact Storage", "Ready in Minutes", "Emergency Preparedness"],
      },
      {
        number: "05",
        title: "Celebrity Food Lines",
        short: "Premium co-branded lines built with athletes and media personalities.",
        description:
          "We create premium food brands together with celebrities, athletes, influencers and media personalities. This includes recipe development, branding, packaging, manufacturing and worldwide distribution.",
        note: "Example: Jakub Vágner, internationally recognized fisherman and former National Geographic & Discovery personality.",
        benefits: [
          "Celebrity branding",
          "Premium packaging",
          "Worldwide distribution",
          "Retail-ready products",
          "Social media marketing",
          "Global manufacturing",
          "Complete brand management",
          "24 months shelf life",
        ],
        tags: ["Celebrity Branding", "Global Manufacturing", "Worldwide Distribution", "24 Months Shelf Life"],
      },
      {
        number: "06",
        title: "White Label Manufacturing",
        short: "Turnkey private-label production under your own brand.",
        description:
          "We develop and manufacture complete ready-to-eat food collections under our partners' own brands. From recipe development to packaging design, multilingual labeling and worldwide distribution, we provide a complete turnkey solution.",
        benefits: [
          "24 months shelf life",
          "OEM manufacturing",
          "Multilingual packaging",
          "European manufacturing",
          "Private label production",
          "Custom recipes",
          "Worldwide logistics",
          "Flexible production volumes",
        ],
        tags: ["24 Months Shelf Life", "OEM Manufacturing", "Custom Recipes", "Worldwide Logistics", "European Manufacturing"],
      },
      {
        number: "07",
        title: "Protein Bomb Fitness Collection",
        short: "48–49g protein, sous-vide cooked, built for athletes.",
        description:
          "High-protein, sous-vide cooked meat collection designed for athletes, fitness enthusiasts and active lifestyles.",
        note: "Developed in partnership with Karel Vémola, MMA legend and global fitness ambassador.",
        benefits: [
          "48–49g protein per pack",
          "Sous-vide cooked",
          "High in protein",
          "24 months shelf life",
          "Ready to eat",
          "No refrigeration required",
          "2×250g vacuum packs",
          "Built for performance",
        ],
        tags: ["48–49g Protein", "Sous-Vide Cooked", "High Protein", "No Refrigeration", "24 Months Shelf Life"],
      },
      {
        number: "08",
        title: "Instant Power Bowl",
        short: "Instant noodle cups — just add hot water, ready in three minutes.",
        description:
          "Premium instant noodle cups designed for office workers, students, travel and everyday convenience. Just add hot water and enjoy a real meal, anywhere, anytime.",
        benefits: [
          "Just add hot water",
          "Ready in 3 minutes",
          "High in protein",
          "Real ingredients",
          "Convenient & portable",
          "Lightweight",
          "Long shelf life",
          "Perfect for travel",
        ],
        tags: ["Just Add Hot Water", "Ready in 3 Minutes", "High Protein", "Real Ingredients", "Portable"],
      },
    ],
  },
  ask: {
    lookingFor: {
      kicker: "Who We Are Looking For",
      title: "Strategic partners to scale the platform worldwide.",
      intro:
        "We are seeking long-term strategic partners and distributors to expand our Global Ready-to-Eat Meal Platform worldwide.",
      groups: [
        {
          title: "Governments & Public Sector",
          items: ["Governments", "Military & Defence", "Civil Protection", "Humanitarian Organizations", "Emergency Agencies"],
        },
        {
          title: "Food & Retail Partners",
          items: ["Food Manufacturers", "Food Distributors", "Retail Chains", "Online Grocery Platforms", "Convenience Store Networks"],
        },
        {
          title: "Strategic & Commercial Partners",
          items: ["Investment Funds", "Family Offices", "Private Equity", "Hospitality & Airlines", "Global Strategic Partners"],
        },
      ],
      closing: "Looking for strategic partners to build the world's leading Ready-to-Eat Food Platform.",
    },
    closing: {
      lines: [
        "The world doesn't need another food company.",
        "The world needs food without limits.",
        "Food that crosses borders.",
        "Food that reaches disaster zones.",
        "Food that feeds communities.",
        "Food that supports governments.",
        "Food that helps families prepare.",
        "Food that creates new opportunities for global brands.",
        "That is why Real Meal exists.",
      ],
      tagline: "Food without borders. Ready for the world.",
    },
  },
  contact: {
    kicker: "Contact Us",
    title: "Let's build the future of food together.",
    subtitle: "Food without borders. Ready for the world.",
    photoAlt: "Portrait of {name}",
    people: [
      {
        name: "Tomáš Skácel",
        role: "Founder | Shareholder | Global CEO",
        photo: "/team/skacel.webp",
        phone: "+420 606 806 060",
        email: "tomas.skacel@astrafood.cz",
      },
      {
        name: "Ondřej Pernecký",
        role: "Global Business Development & Sales Director",
        photo: "/team/pernecky.webp",
        phone: "+420 739 177 819",
        email: "ondrej.pernecky@astrafood.cz",
      },
      {
        name: "Karel Vágner",
        role: "Shareholder | Managing Partner | Global Business Development & Strategic Partnerships",
        photo: "/team/vagner.webp",
        phone: "+420 602 312 154",
        email: "karel.vagner@real-meal.cz",
        instagram: "@karelvagner",
      },
      {
        name: "Simona Krainová",
        role: "Shareholder | Global Brand Ambassador | Humanitarian & Social Impact Ambassador",
        photo: "/team/krainova.webp",
        instagram: "@simonakrainova",
        note: "Top model, influencer, traveler",
      },
    ],
    form: {
      name: "Full name",
      email: "Email",
      company: "Company / Organization",
      message: "Tell us about your partnership interest",
      submit: "Send Inquiry",
      success: "Thank you, we'll be in touch.",
      responseTime: "We reply to partnership enquiries within 2 business days.",
      privacy: "Your details are used only to answer this enquiry and are never shared with third parties.",
    },
    footer: {
      note: "Real Meal Global — a strategic partnership between Real Meal and Astra Food.",
      links: "astrafood.cz · real-meal.cz · real-mealglobal.com",
      copyright: "Real Meal Global. All rights reserved.",
    },
  },
};
